name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ STM32F103RC_btt_512K ]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - uses: actions/cache@v2
      with:
        path: |
          ~/.platformio
          .pio
        key: ${{ runner.os }}-pio-run-${{ hashFiles('.pio/build/project.checksum') }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run PlatformIO
      run: platformio run --environment ${{ matrix.target }}
    - uses: actions/upload-artifact@master
      with:
        name: ${{ github.event.repository.name }}-firmware-${{ matrix.target }}
        path: .pio/build/${{ matrix.target }}/firmware.*
